spring:
  application:
    name: rest-spring-boot

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_spring_boot_ana?useTimeZone=true&serverTimezone=UTC
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

  # logging de SQL pode ser útil para debug
  # show-sql: true
